// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVMWLwT_pPOf-WBZ-TbryVgFh2LdG6G9s',
    appId: '1:861306810038:web:71eeff9d163357c9334017',
    messagingSenderId: '861306810038',
    projectId: 'toku-app-9bf69',
    authDomain: 'toku-app-9bf69.firebaseapp.com',
    storageBucket: 'toku-app-9bf69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcRLlB9tA7iCkKF5lcuEThc00YluSNL5A',
    appId: '1:861306810038:android:ae78160a9b53a6c1334017',
    messagingSenderId: '861306810038',
    projectId: 'toku-app-9bf69',
    storageBucket: 'toku-app-9bf69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSMwkba5PRRBCgS71IxEEtaRDbu0kfdTA',
    appId: '1:861306810038:ios:575f0ee5fbda2ac4334017',
    messagingSenderId: '861306810038',
    projectId: 'toku-app-9bf69',
    storageBucket: 'toku-app-9bf69.firebasestorage.app',
    iosBundleId: 'com.example.tokuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSMwkba5PRRBCgS71IxEEtaRDbu0kfdTA',
    appId: '1:861306810038:ios:575f0ee5fbda2ac4334017',
    messagingSenderId: '861306810038',
    projectId: 'toku-app-9bf69',
    storageBucket: 'toku-app-9bf69.firebasestorage.app',
    iosBundleId: 'com.example.tokuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVMWLwT_pPOf-WBZ-TbryVgFh2LdG6G9s',
    appId: '1:861306810038:web:14d74e20ed5ee956334017',
    messagingSenderId: '861306810038',
    projectId: 'toku-app-9bf69',
    authDomain: 'toku-app-9bf69.firebaseapp.com',
    storageBucket: 'toku-app-9bf69.firebasestorage.app',
  );

}